### ISSUE TITLE
我找不到Core.framework这个文件

### ISSUE THREAD

**Issue by hanyaping** [ipfs-shipyard/gomobile-ipfs#47] opened 2020-08-17 12:52 UTC
<img width="708" alt="22222" src="https://user-images.githubusercontent.com/17908865/90398108-74c0d980-e0cb-11ea-94f5-d91e344b6a19.png">
<img width="563" alt="11111" src="https://user-images.githubusercontent.com/17908865/90398115-768a9d00-e0cb-11ea-8308-b04f998dad04.png">

**Comment by aeddi** [comment] 2020-08-17 12:59
Hello,
Please don't create an issue without any description / comment to explain your problem, especially since it seems to be a duplicate of another issue I gave you the solution to and you didn't answer: #45

**Closed** 2020-08-18 09:04 UTC
